### ISSUE TITLE
Implement class to send messages to the Github API

### ISSUE THREAD

**Issue by marten-voorberg** [marten-voorberg/SEF-CICD#4]
There should be a concrete implemenation of the `GithubAPIClient` interface that allows users of the API to set the status on a certain commit. 

For details of the protocol, see [this](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28).

Please keep in mind that the authorization token is a secret and should not end up in the repository! IMO it should be in a file `/secrets/github-api-key` that everyone creates themselves. See [this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) webpage about creating an authentication token.

For this issue, you probably need to import some HTTP client library. Please do this through Gradle.

**Comment by dague1** [comment]
I will look into this.
